name: Delete old workflow runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 3'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs@v0.1.0
        with:
          repository: BPower0036/chess
          older-than-seconds: 604,800
          what-if: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
